// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanDiego.API.Data;

#nullable disable

namespace SanDiego.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240414103937_FixUselessFunction")]
    partial class FixUselessFunction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SanDiego.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SanDiego.API.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoomStatus")
                        .HasColumnType("int");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://media.cnn.com/api/v1/images/stellar/prod/140127103345-peninsula-shanghai-deluxe-mock-up.jpg?q=w_2226,h_1449,x_0,y_0,c_fill",
                            Price = 50,
                            RoomNumber = 101,
                            RoomStatus = 0,
                            RoomType = 0
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://www.seleqtionshotels.com/content/dam/seleqtions/Connaugth/TCPD_PremiumBedroom4_1235.jpg/jcr:content/renditions/cq5dam.web.1280.1280.jpeg",
                            Price = 80,
                            RoomNumber = 102,
                            RoomStatus = 0,
                            RoomType = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://static.dezeen.com/uploads/2021/07/eaton-dc-interiors-hotel-washington-dc-maryland-usa-adrian-gaut_dezeen_2364_col_2.jpg",
                            Price = 120,
                            RoomNumber = 103,
                            RoomStatus = 0,
                            RoomType = 2
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://www.redrockresort.com/wp-content/uploads/2020/12/RR-Standard-2-Queen.jpg",
                            Price = 50,
                            RoomNumber = 201,
                            RoomStatus = 1,
                            RoomType = 0
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://www.theshelbourne.com/resourcefiles/roomssmallimages/heritage-parkview-guestroom.jpg?version=2292024113454",
                            Price = 80,
                            RoomNumber = 202,
                            RoomStatus = 3,
                            RoomType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
